### ISSUE TITLE
API Syntax, supporting more complex state objects

### ISSUE THREAD

**Issue by jessehouchins** [kevinmarx/viewstate#1]
I suggest renaming the code methods to `set/unset` instead of `add/remove`. That way `add/remove` can be reserved for group states.

```
// Contructor methods

ViewState.set('foo')                    // Init new boolean
ViewState.set('nested', ['foo', 'bar']) // initialize new nested state (when arguments are strings)
ViewState.set('group', [])              // initialize new group (when no arguments, or arguments are objects)

// Group methods - these will all auto initialize the group if it does not exist.

ViewState.add('group', someModels)      // add to group
ViewState.remove('group', otherModels)  // remove from group
ViewState.reset('group', newModels)     // reset group with only the new models

// Unset state

ViewState.unset('foo')                  // Clear any state type
ViewState.unset('nested', ['foo'])      // unset nested property
```

**Comment by kevinmarx** [comment]
ViewState was made for tracking the state of the DOM which is heavily relient on the state of data, however, it is not storing the state of the data itself. It seems this enhancement would be tracking data states and it is my opinion that they should then belong in an actual collection/model.

I could potentially see adding this functionality through an add-on module since this greatly changes the behavior.
